# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: the_market_cat_development

test:
  <<: *default
  database: the_market_cat_test

production:
  <<: *default
  url: "postgres://u8b1thgitdphtl:pa74f500f005cdd2d87191e6a67b36039fc48fdb4a02fb048e434c96f1bb1420c@cd27da2sn4hj7h.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d9d84qiotjitm9"
  database: the_market_cat_production
