# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: the_market_cat_development

test:
  <<: *default
  database: the_market_cat_test

production:
  <<: *default
  # Utilisation de DATABASE_URL configurée automatiquement par Heroku
  url: <%= ENV['DATABASE_URL'] %>
